services:
  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortener:1.0.0
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped